version: "3.9"

services:
  endpointhub:
    image: registry.gitlab.com/user/project:latest
    container_name: endpointhub
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./model:/app/model
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
